# Site settings
title: Fluentast
email: hansjrgschroedl@gmail.com
description: >
  The fluent way to create Java code 

baseurl: "/FluentAST"
url: https://hschroedl.at
git_address: https://github.com/hschroedl/FluentAST
git_edit_address: https://github.com/hschroedl/FluentAST/blob/master/docs/

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _docs/fluentast-core
    type: docs
  values:
    layout: docs_generated
    sectionid: docs/fluentast-core
    seo:
      type: "WebPage"

collections:
  docs:
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
